"""GENERATED baseline for the strict-coverage ratchet (#784).

Do not edit counts by hand. Regenerate after reducing strict
errors with:

    nix-shell --run "python3 -m tests._strict_ratchet_scanner" \
        > tests/_strict_ratchet_baseline.py
"""

STRICT_RATCHET_BASELINE: dict[str, int] = {
    "cratedigger.py": 1,
    "harness/beets_harness.py": 1,
    "lib/artist_releases.py": 70,
    "lib/audio_hash.py": 3,
    "lib/beets.py": 12,
    "lib/beets_db.py": 3,
    "lib/beets_delete.py": 9,
    "lib/beets_distance.py": 66,
    "lib/browse.py": 3,
    "lib/config.py": 35,
    "lib/context.py": 12,
    "lib/disk_coverage_service.py": 1,
    "lib/dispatch/outcome_actions.py": 1,
    "lib/dispatch/post_import.py": 3,
    "lib/dispatch/quality_gate.py": 2,
    "lib/dispatch/types.py": 1,
    "lib/download.py": 30,
    "lib/download_reconstruction.py": 3,
    "lib/download_recovery.py": 26,
    "lib/download_rejection.py": 9,
    "lib/download_validation.py": 6,
    "lib/enqueue.py": 14,
    "lib/field_resolver_service.py": 62,
    "lib/import_preview.py": 1,
    "lib/import_queue.py": 2,
    "lib/matching.py": 9,
    "lib/measurement.py": 7,
    "lib/migrator.py": 15,
    "lib/peer_cache.py": 1,
    "lib/pipeline_db/_core.py": 4,
    "lib/pipeline_db/_shared.py": 4,
    "lib/pipeline_db/dashboard.py": 83,
    "lib/pipeline_db/import_jobs.py": 2,
    "lib/pipeline_db/misc.py": 1,
    "lib/pipeline_db/requests.py": 45,
    "lib/pipeline_db/search_plan.py": 15,
    "lib/pipeline_db/terminal_outcomes.py": 5,
    "lib/pipeline_db/transfer_ledger.py": 1,
    "lib/pipeline_db/youtube.py": 2,
    "lib/quality/__init__.py": 2,
    "lib/quality/decisions.py": 8,
    "lib/quality/download_state.py": 6,
    "lib/quality/evidence_types.py": 1,
    "lib/quality/import_result_types.py": 67,
    "lib/quality/pipeline.py": 77,
    "lib/quality/wire_types.py": 4,
    "lib/search.py": 51,
    "lib/search_exec.py": 1,
    "lib/search_plan_inspection.py": 53,
    "lib/search_plan_service.py": 9,
    "lib/slskd_client.py": 17,
    "lib/spectral_check.py": 102,
    "lib/startup_reconciliation.py": 20,
    "lib/terminal_outcomes.py": 1,
    "lib/transitions.py": 1,
    "lib/unfindable_detection_service.py": 3,
    "lib/util.py": 56,
    "lib/v0_probe.py": 1,
    "lib/validation_envelope.py": 1,
    "lib/world_invariants.py": 1,
    "lib/wrong_match_cleanup_service.py": 1,
    "lib/youtube_album_service.py": 146,
    "lib/youtube_ingest_service.py": 14,
    "scripts/bench_parallel_search.py": 2,
    "scripts/pipeline_cli/quality.py": 1,
    "tools/generate-ai-adapters.py": 14,
    "web/cache.py": 6,
    "web/routes/browse.py": 3,
    "web/routes/pipeline_mutations.py": 5,
}
