"""GENERATED tests escape-hatch freeze baseline (#784).

Frozen at campaign end; may only DECREASE. Tests are never
strict-annotated, but their Any/cast/type-ignore debt must not grow.
Regenerate after REMOVING hatches from tests with:

    nix-shell --run "python3 -m tests._typing_ratchet_scanner tests" \
        > tests/_tests_typing_ratchet_baseline.py
"""

TESTS_TYPING_RATCHET_BASELINE: dict[str, dict[str, int]] = {
    "tests/_lambda_audit.py": {"type_ignore": 1},
    "tests/beets_world.py": {"any": 2, "type_ignore": 3},
    "tests/fakes/_shared.py": {"any": 2},
    "tests/fakes/beets.py": {"any": 18},
    "tests/fakes/cursors.py": {"any": 4},
    "tests/fakes/daily_flake_update.py": {"any": 4},
    "tests/fakes/deploy_cycle.py": {"any": 2},
    "tests/fakes/deploy_pin.py": {"any": 4},
    "tests/fakes/lookups.py": {"any": 9},
    "tests/fakes/pipeline_db.py": {"any": 162, "cast": 24, "type_ignore": 1},
    "tests/fakes/rows.py": {"any": 6},
    "tests/fakes/slskd.py": {"any": 48},
    "tests/fakes/ytmusic.py": {"any": 13},
    "tests/helpers.py": {"any": 25},
    "tests/read_projection_registry.py": {"any": 34},
    "tests/test_album_source.py": {"type_ignore": 3},
    "tests/test_artist_compare.py": {"cast": 3},
    "tests/test_artist_compare_generated.py": {"cast": 4},
    "tests/test_audio_hash.py": {"type_ignore": 1},
    "tests/test_beets_album_op.py": {"type_ignore": 1},
    "tests/test_beets_db.py": {"any": 2, "type_ignore": 2},
    "tests/test_beets_destructive_configs_generated.py": {"any": 3},
    "tests/test_beets_validation.py": {"type_ignore": 1},
    "tests/test_browse.py": {"any": 7, "cast": 5},
    "tests/test_browse_route_generated.py": {"type_ignore": 2},
    "tests/test_cleanup_ghost_imported_generated.py": {"cast": 2},
    "tests/test_config.py": {"type_ignore": 2},
    "tests/test_convergence_runner_generated.py": {"cast": 4},
    "tests/test_conversion_e2e.py": {"type_ignore": 1},
    "tests/test_cooldown.py": {"type_ignore": 1},
    "tests/test_cycle_summary.py": {"cast": 3},
    "tests/test_deploy_cycle_verifier_generated.py": {"any": 2},
    "tests/test_deploy_pin_generated.py": {"any": 2},
    "tests/test_discogs_api.py": {"type_ignore": 4},
    "tests/test_discogs_artist_bulk_generated.py": {"any": 33},
    "tests/test_discogs_fail_closed.py": {"any": 2},
    "tests/test_disk_coverage_service.py": {"cast": 5},
    "tests/test_disk_reaper_generated.py": {"any": 8},
    "tests/test_dispatch_core.py": {"type_ignore": 10},
    "tests/test_dispatch_from_db.py": {"any": 1, "cast": 1, "type_ignore": 12},
    "tests/test_dispatch_outcomes_generated.py": {"any": 2, "cast": 2, "type_ignore": 5},
    "tests/test_do_mark.py": {"type_ignore": 2},
    "tests/test_download.py": {"any": 65, "cast": 57, "type_ignore": 1},
    "tests/test_download_errors_generated.py": {"any": 10},
    "tests/test_download_reducer.py": {"type_ignore": 3},
    "tests/test_enqueue_fanout.py": {"any": 2, "cast": 14},
    "tests/test_evidence_generated.py": {"any": 12, "cast": 4},
    "tests/test_fakes.py": {"any": 10, "cast": 4, "type_ignore": 4},
    "tests/test_field_resolver_service.py": {"any": 8, "type_ignore": 5},
    "tests/test_force_import_gates.py": {"type_ignore": 8},
    "tests/test_grab_list.py": {"type_ignore": 6},
    "tests/test_harness_config_guard.py": {"any": 4, "cast": 5},
    "tests/test_harness_mutation_log.py": {"any": 3},
    "tests/test_harness_serialization.py": {"any": 4},
    "tests/test_import_dispatch.py": {"type_ignore": 26},
    "tests/test_import_manifest.py": {"any": 7, "cast": 7},
    "tests/test_import_manifest_generated.py": {"cast": 2},
    "tests/test_import_one_stages.py": {"any": 2, "cast": 2},
    "tests/test_import_operation_fence.py": {"any": 11, "cast": 7},
    "tests/test_import_operation_fence_generated.py": {"type_ignore": 1},
    "tests/test_import_preview.py": {"any": 8, "cast": 3},
    "tests/test_import_queue.py": {"any": 81, "cast": 47},
    "tests/test_import_result.py": {"type_ignore": 4},
    "tests/test_integration.py": {"type_ignore": 1},
    "tests/test_integration_slices.py": {"any": 48, "cast": 28, "type_ignore": 35},
    "tests/test_jellyfin_pins_generated.py": {"type_ignore": 1},
    "tests/test_library_artist_service.py": {"cast": 2},
    "tests/test_lossless_lineage_check_generated.py": {"type_ignore": 1},
    "tests/test_matching.py": {"any": 11, "cast": 5},
    "tests/test_materialize_generated.py": {"any": 2},
    "tests/test_mb_artist_provenance_generated.py": {"any": 3},
    "tests/test_mbid_replace_service.py": {"cast": 3},
    "tests/test_measurement.py": {"any": 3, "cast": 3, "type_ignore": 6},
    "tests/test_measurement_failure.py": {"type_ignore": 1},
    "tests/test_multidisc_manifest_generated.py": {"any": 2, "cast": 2},
    "tests/test_owned_section_expansion_generated.py": {"type_ignore": 2},
    "tests/test_peer_cache.py": {"any": 9},
    "tests/test_pin_retention_generated.py": {"type_ignore": 2},
    "tests/test_pipeline_cli.py": {"any": 66, "cast": 57},
    "tests/test_pipeline_db.py": {"any": 32, "cast": 23},
    "tests/test_pipeline_db_column_contract.py": {"cast": 4},
    "tests/test_preview_failure_evidence_generated.py": {"any": 13, "cast": 5},
    "tests/test_quality_decisions.py": {"any": 5, "type_ignore": 1},
    "tests/test_quality_evidence.py": {"cast": 3, "type_ignore": 7},
    "tests/test_quality_generated.py": {"type_ignore": 2},
    "tests/test_repair_cli.py": {"any": 14, "cast": 14},
    "tests/test_request_finalization.py": {"any": 2, "cast": 2, "type_ignore": 1},
    "tests/test_search_classification.py": {"type_ignore": 1},
    "tests/test_search_exec.py": {"any": 13, "type_ignore": 13},
    "tests/test_search_plan_service.py": {"cast": 3},
    "tests/test_slskd_client.py": {"cast": 2, "type_ignore": 5},
    "tests/test_slskd_searches.py": {"any": 5},
    "tests/test_spectral_attempt_audit_generated.py": {"any": 11, "type_ignore": 2},
    "tests/test_terminal_outcome_callers.py": {"any": 3, "cast": 3},
    "tests/test_terminal_outcomes.py": {"any": 4, "cast": 2},
    "tests/test_transfer_ledger_generated.py": {"type_ignore": 1},
    "tests/test_transitions.py": {"any": 25, "cast": 26, "type_ignore": 1},
    "tests/test_triage_service.py": {"type_ignore": 2},
    "tests/test_unfindable_detection_service.py": {"any": 18, "type_ignore": 4},
    "tests/test_validation_result.py": {"type_ignore": 3},
    "tests/test_web_cache.py": {"any": 5, "type_ignore": 1},
    "tests/test_web_cache_generated.py": {"any": 11},
    "tests/test_web_dev_server_generated.py": {"any": 4, "type_ignore": 1},
    "tests/test_world_invariants.py": {"type_ignore": 1},
    "tests/test_wrong_match_cleanup_service.py": {"cast": 3},
    "tests/test_wrong_matches_cleanup.py": {"cast": 5},
    "tests/test_youtube_album_service.py": {"any": 15, "cast": 3, "type_ignore": 4},
    "tests/test_youtube_ingest_service.py": {"any": 12, "cast": 2},
    "tests/test_youtube_ingest_worker.py": {"any": 35, "cast": 2, "type_ignore": 2},
    "tests/test_youtube_mapping_write_generated.py": {"any": 3},
    "tests/web/test_routes_labels.py": {"type_ignore": 2},
    "tests/world_model/support.py": {"any": 8},
}
