"""GENERATED baseline for the typing escape-hatch ratchet (#765).

Do not edit counts by hand. Regenerate after removing escape
hatches with:

    nix-shell --run "python3 -m tests._typing_ratchet_scanner" \
        > tests/_typing_ratchet_baseline.py
"""

TYPING_RATCHET_BASELINE: dict[str, dict[str, int]] = {
    "cratedigger.py": {"any": 5},
    "lib/beets_delete.py": {"any": 5},
    "lib/browse.py": {"any": 18},
    "lib/context.py": {"any": 23},
    "lib/destructive_release_service.py": {"any": 9},
    "lib/disk_coverage_service.py": {"any": 5},
    "lib/dispatch/evidence_gate.py": {"any": 1},
    "lib/dispatch/outcome_actions.py": {"any": 4},
    "lib/download.py": {"any": 4},
    "lib/download_materialization.py": {"any": 2},
    "lib/download_reconstruction.py": {"any": 2},
    "lib/download_rejection.py": {"any": 3},
    "lib/enqueue.py": {"any": 21},
    "lib/field_resolver_service.py": {"any": 43},
    "lib/import_evidence.py": {"any": 3},
    "lib/import_manifest.py": {"any": 3},
    "lib/import_preview.py": {"any": 7},
    "lib/import_queue.py": {"any": 18},
    "lib/jellyfin_pin_service.py": {"any": 2},
    "lib/json_narrow.py": {"any": 3},
    "lib/long_tail_service.py": {"any": 6},
    "lib/matching.py": {"any": 8},
    "lib/mbid_replace_service.py": {"any": 11},
    "lib/measurement.py": {"any": 2},
    "lib/peer_cache.py": {"any": 8},
    "lib/pipeline_db/_core.py": {"any": 13},
    "lib/pipeline_db/_shared.py": {"any": 30},
    "lib/pipeline_db/dashboard.py": {"any": 22},
    "lib/pipeline_db/download_log.py": {"any": 4},
    "lib/pipeline_db/evidence.py": {"any": 3},
    "lib/pipeline_db/import_jobs.py": {"any": 10},
    "lib/pipeline_db/jellyfin_pins.py": {"any": 2},
    "lib/pipeline_db/misc.py": {"any": 13},
    "lib/pipeline_db/plex_pins.py": {"any": 2},
    "lib/pipeline_db/requests.py": {"any": 13},
    "lib/pipeline_db/search_ledger.py": {"any": 2},
    "lib/pipeline_db/search_plan.py": {"any": 7},
    "lib/pipeline_db/terminal_outcomes.py": {"any": 6},
    "lib/pipeline_db/transfer_ledger.py": {"any": 2},
    "lib/pipeline_db/youtube.py": {"any": 10},
    "lib/plex_pin_service.py": {"any": 2},
    "lib/quality/dispatch_actions.py": {"any": 2},
    "lib/quality/filetypes.py": {"any": 5},
    "lib/quality/import_result_types.py": {"any": 8},
    "lib/quality/pipeline.py": {"any": 5},
    "lib/quality/ranks.py": {"any": 2},
    "lib/quality_evidence.py": {"any": 6},
    "lib/release_snapshot.py": {"any": 6},
    "lib/repair.py": {"any": 4},
    "lib/search.py": {"any": 17},
    "lib/search_exec.py": {"any": 9},
    "lib/search_plan_inspection.py": {"any": 21},
    "lib/search_plan_service.py": {"any": 30},
    "lib/slskd_client.py": {"any": 13},
    "lib/slskd_events.py": {"any": 9},
    "lib/slskd_searches.py": {"any": 5},
    "lib/slskd_transfers.py": {"any": 11},
    "lib/transitions.py": {"any": 7},
    "lib/triage_service.py": {"any": 16},
    "lib/unfindable_detection_service.py": {"any": 9},
    "lib/util.py": {"any": 10},
    "lib/validation_envelope.py": {"any": 5},
    "lib/world_audit_service.py": {"any": 4},
    "lib/world_invariants.py": {"any": 4},
    "lib/wrong_match_cleanup_service.py": {"any": 14},
    "lib/wrong_match_delete_service.py": {"any": 2},
    "lib/wrong_matches.py": {"any": 3},
    "lib/youtube_album_service.py": {"any": 16},
    "lib/youtube_ingest_service.py": {"any": 33},
    "scripts/import_preview_worker.py": {"any": 17},
    "scripts/importer.py": {"any": 7},
    "scripts/pipeline_cli/long_tail.py": {"any": 3},
    "scripts/pipeline_cli/routes_meta.py": {"cast": 4},
    "scripts/pipeline_cli/search_plan.py": {"any": 6},
    "scripts/pipeline_cli/show.py": {"any": 6},
    "scripts/pipeline_cli/triage.py": {"any": 5},
    "scripts/pipeline_cli/youtube.py": {"any": 12},
    "scripts/youtube_ingest_worker.py": {"any": 7},
    "tools/generate-ai-adapters.py": {"any": 8},
    "web/cache.py": {"any": 7},
    "web/classify.py": {"any": 8},
    "web/discogs.py": {"any": 2},
    "web/mb.py": {"any": 2},
    "web/overlay.py": {"any": 2},
    "web/routes/_pydantic.py": {"any": 4},
    "web/routes/imports.py": {"any": 2},
    "web/routes/pipeline_mutations.py": {"any": 5},
    "web/routes/youtube.py": {"any": 15},
    "web/triage_runner.py": {"any": 8},
    "web/wrong_match_file_service.py": {"any": 8},
}
