-- 014_persisted_search_plans.sql - Persist per-request search plans.
--
-- U1 of feat: persisted search plans. Adds the durable plan schema and
-- search-log plan-context fields that later units (plan generator, persistence
-- service, executor cutover, inspection) will read and write.
--
-- Design notes:
--
--   * Additive and rollback-compatible: new tables, new nullable columns on
--     existing tables, no DDL changes to currently-shipped columns. Old code
--     can keep reading/writing album_requests and search_log as before.
--   * search_plans records every generation attempt -- successful and failed
--     -- with provenance and an optional sanitized error blob.
--   * search_plan_items lists the runnable queries for a plan with a stable
--     ordinal cursor. Non-empty runnable query and unique (plan, ordinal) are
--     CHECK / UNIQUE-enforced.
--   * album_requests gains active_plan_id, next_plan_ordinal, plan_cycle_count
--     so the cursor lives on the request row -- search_attempts becomes
--     scheduler-only.
--   * search_log gains nullable plan-context columns plus execution-stage,
--     attempt_consumed, cursor_update_status, stale_reason, plan_cycle_snapshot
--     audit markers. Historical rows (NULL plan context) remain valid.
--   * Active-plan / request ownership is enforced by a composite FK from
--     album_requests(active_plan_id, id) -> search_plans(id, request_id) with
--     PostgreSQL 15+ "ON DELETE SET NULL (column)" so plan deletion only nulls
--     the cursor, not the request's primary key.
--   * One active plan per request is enforced by a partial unique index on
--     search_plans(request_id) WHERE status = 'active'.
--   * Historical search_log.outcome = 'exhausted' rows remain valid; the
--     CHECK constraint is unchanged in this migration.

-- ---------------------------------------------------------------------------
-- search_plans: per-request plan generation attempts (successful + failed)
-- ---------------------------------------------------------------------------

CREATE TABLE search_plans (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL
        REFERENCES album_requests(id) ON DELETE CASCADE,

    -- Generator identity. Bumped manually whenever generation-affecting code
    -- or config changes. Plans whose generator_id != current generator_id are
    -- "old-generator" and will be regenerated by startup reconciliation.
    generator_id TEXT NOT NULL,

    -- Plan lifecycle status.
    --   active                 = current successful plan for this request
    --   superseded             = was active, replaced by a newer successful plan
    --   failed_deterministic   = generation failed with a sticky deterministic
    --                            cause (e.g. no runnable query for any tier)
    --   failed_transient       = generation failed transiently (resolver outage,
    --                            DB hiccup) and may be retried later
    status TEXT NOT NULL CHECK (status IN (
        'active', 'superseded', 'failed_deterministic', 'failed_transient'
    )),

    -- Failure classifier (NULL for successful plans). Free-form TEXT inside a
    -- known-values whitelist so future units can grow the taxonomy without a
    -- new migration; for now the list is small and stable.
    failure_class TEXT CHECK (failure_class IS NULL OR failure_class IN (
        'no_runnable_query',     -- deterministic: no artist/title/track query
        'metadata_incomplete',   -- deterministic: missing required fields
        'resolver_unavailable',  -- transient: external resolver down
        'dependency_failure',    -- transient: generic upstream dependency
        'unknown'                -- catch-all; keep small set above otherwise
    )),

    -- Snapshot of the release metadata used to generate this plan. JSONB so
    -- inspection and per-plan reproduction can read what the generator saw.
    metadata_snapshot JSONB,

    -- Generator provenance: dropped tokens, deduped variants, omitted
    -- candidates, etc. Bounded by the application before insert.
    provenance JSONB,

    -- Sanitized human-readable error. Application sanitizes/truncates before
    -- writing so credentials and host paths never land here.
    error_message TEXT,

    -- Supersession trail: when a successful regeneration replaces an existing
    -- active plan, the old plan flips to status='superseded' and points at
    -- the replacement here.
    superseded_at TIMESTAMPTZ,
    superseded_by_plan_id INTEGER
        REFERENCES search_plans(id) ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Composite-unique key required by the album_requests active_plan_id FK
    -- below. id is already PK so this is logically redundant, but the FK
    -- needs to reference both columns to enforce active-plan / request
    -- ownership at the DB level.
    UNIQUE (id, request_id)
);

-- Lookup indexes
CREATE INDEX idx_search_plans_request_status
    ON search_plans (request_id, status);
CREATE INDEX idx_search_plans_generator
    ON search_plans (generator_id);
CREATE INDEX idx_search_plans_request_created_at
    ON search_plans (request_id, created_at DESC);

-- One active plan per request, enforced as a partial unique index so
-- failed/superseded rows can coexist with a single active row.
CREATE UNIQUE INDEX uniq_search_plans_one_active_per_request
    ON search_plans (request_id) WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- search_plan_items: runnable queries for a plan
-- ---------------------------------------------------------------------------

CREATE TABLE search_plan_items (
    id SERIAL PRIMARY KEY,
    plan_id INTEGER NOT NULL
        REFERENCES search_plans(id) ON DELETE CASCADE,

    -- Cursor position within the plan, 0-indexed. Unique per (plan, ordinal).
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),

    -- Strategy label for the slot ("default", "unwild", "unwild_year",
    -- "track_<idx>", etc.). Free-form TEXT so the generator can evolve labels
    -- without a migration.
    strategy TEXT NOT NULL,

    -- Runnable query string. CHECK-enforced non-empty (after stripping
    -- ASCII whitespace) so successful plans cannot ship blank slots.
    query TEXT NOT NULL
        CHECK (length(btrim(query, E' \t\n\r\f\v')) > 0),

    -- Canonical/normalized query key for dedupe and per-query usefulness
    -- aggregation. May equal `query` after normalization.
    canonical_query_key TEXT,

    -- Repeat-group identifier so a tier that intentionally repeats a default
    -- query across multiple ordinals shares one group while remaining
    -- distinct slots. NULL = standalone slot.
    repeat_group TEXT,

    -- Per-item generator provenance (e.g. low-entropy tokens dropped, dedupe
    -- runners-up). Bounded by the application before insert.
    provenance JSONB,

    UNIQUE (plan_id, ordinal),

    -- Composite FK target for search_log(plan_item_id, plan_id). id is
    -- already PK; this redundant key lets the DB enforce that a logged
    -- plan_item_id belongs to the logged plan_id.
    UNIQUE (id, plan_id)
);

CREATE INDEX idx_search_plan_items_plan_ordinal
    ON search_plan_items (plan_id, ordinal);
CREATE INDEX idx_search_plan_items_canonical_key
    ON search_plan_items (canonical_query_key);

-- ---------------------------------------------------------------------------
-- album_requests: cursor / active-plan fields
-- ---------------------------------------------------------------------------

ALTER TABLE album_requests
    ADD COLUMN active_plan_id INTEGER,
    ADD COLUMN next_plan_ordinal INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN plan_cycle_count INTEGER NOT NULL DEFAULT 0;

-- Composite FK enforces that active_plan_id, when set, points at a plan
-- belonging to the same request. PostgreSQL 15+ "ON DELETE SET NULL (col)"
-- only nulls active_plan_id when the referenced plan is deleted -- the
-- request's primary key id stays intact.
ALTER TABLE album_requests
    ADD CONSTRAINT album_requests_active_plan_owner_fkey
    FOREIGN KEY (active_plan_id, id)
    REFERENCES search_plans (id, request_id)
    ON DELETE SET NULL (active_plan_id);

-- next_plan_ordinal must be sane.
ALTER TABLE album_requests
    ADD CONSTRAINT album_requests_next_plan_ordinal_nonneg_check
    CHECK (next_plan_ordinal >= 0);

ALTER TABLE album_requests
    ADD CONSTRAINT album_requests_plan_cycle_count_nonneg_check
    CHECK (plan_cycle_count >= 0);

-- All-wanted reconciliation index. Supports startup's ignore-page-size
-- /ignore-retry-eligibility scan for wanted rows missing an active plan,
-- or carrying an old-generator plan.
CREATE INDEX idx_album_requests_wanted_active_plan
    ON album_requests (status, active_plan_id)
    WHERE status = 'wanted';

-- ---------------------------------------------------------------------------
-- search_log: plan-context audit fields
-- ---------------------------------------------------------------------------
--
-- Every column is nullable so historical rows (created before this migration)
-- remain valid. The CHECK constraint on outcome is intentionally NOT touched:
-- historical 'exhausted' rows stay legal; new code simply stops emitting it.

ALTER TABLE search_log
    ADD COLUMN plan_id INTEGER
        REFERENCES search_plans(id) ON DELETE SET NULL,
    ADD COLUMN plan_item_id INTEGER
        REFERENCES search_plan_items(id) ON DELETE SET NULL,
    ADD COLUMN plan_ordinal INTEGER,
    ADD COLUMN plan_strategy TEXT,
    ADD COLUMN plan_canonical_query_key TEXT,
    ADD COLUMN plan_repeat_group TEXT,
    ADD COLUMN plan_generator_id TEXT,

    -- Stage at which this row was emitted. Lets dashboards distinguish
    -- pre-attempt setup failures from accepted-search outcomes from stale
    -- old-plan completions. NULL on historical rows.
    --   pre_attempt        - submission/setup failed before slskd accepted
    --   accepted           - slskd accepted; outcome is consumed
    --   stale_completion   - completed against a now-superseded plan
    --   reconciliation     - emitted by startup reconciliation, not search
    ADD COLUMN execution_stage TEXT
        CHECK (execution_stage IS NULL OR execution_stage IN (
            'pre_attempt', 'accepted', 'stale_completion', 'reconciliation'
        )),

    -- Whether this attempt consumed a slot (advanced cursor). Pre-attempt
    -- failures and stale completions are non-consuming.
    ADD COLUMN attempt_consumed BOOLEAN,

    -- What happened to the active cursor as a result of this row.
    --   advanced       - ordinal moved forward
    --   wrapped        - wrapped past final ordinal, cycle++ then ordinal=0
    --   unchanged      - non-consuming or stale; cursor not touched
    --   stale          - consumed-attempt but request is on a different plan
    --                    or ordinal now (regenerated mid-flight); log only
    ADD COLUMN cursor_update_status TEXT
        CHECK (cursor_update_status IS NULL OR cursor_update_status IN (
            'advanced', 'wrapped', 'unchanged', 'stale'
        )),

    -- Why this row was flagged stale, when applicable (free-form short tag).
    ADD COLUMN stale_reason TEXT,

    -- Snapshot of the request's plan_cycle_count at the time this row was
    -- written. Lets dashboards bucket usefulness by cycle without needing the
    -- request's current cycle.
    ADD COLUMN plan_cycle_snapshot INTEGER;

ALTER TABLE search_log
    ADD CONSTRAINT search_log_plan_request_fkey
    FOREIGN KEY (plan_id, request_id)
    REFERENCES search_plans (id, request_id)
    ON DELETE SET NULL (plan_id),
    ADD CONSTRAINT search_log_plan_item_owner_fkey
    FOREIGN KEY (plan_item_id, plan_id)
    REFERENCES search_plan_items (id, plan_id)
    ON DELETE SET NULL (plan_item_id);

-- Plan-aware lookup indexes. Old per-request indexes remain.
CREATE INDEX idx_search_log_plan_item
    ON search_log (plan_item_id);
CREATE INDEX idx_search_log_canonical_query_key
    ON search_log (plan_canonical_query_key);
CREATE INDEX idx_search_log_plan_id_created_at
    ON search_log (plan_id, created_at DESC);
