medium_format  # unused variable (album_source.py:27)
foreign_artist_id  # unused variable (album_source.py:54)
db_release_group_year  # unused variable (album_source.py:66)
albumId  # unused variable (cratedigger.py:34)
mediumNumber  # unused variable (cratedigger.py:36)
_.choose_match  # unused method (harness/beets_harness.py:471)
_.choose_item  # unused method (harness/beets_harness.py:499)
_.get_duplicate_action  # unused method (harness/beets_harness.py:566)
_.should_resume  # unused method (harness/beets_harness.py:629)
_.quality_evidence_provenance  # unused attribute (harness/import_one.py:1390)
_.beets_log  # unused attribute (harness/import_one.py:1428)
_.existing_suspect_pct  # unused attribute (harness/import_one.py:1674)
_.v0_verification_bitrate  # unused attribute (harness/import_one.py:2032)
_.beets_log  # unused attribute (harness/import_one.py:2126)
library_status  # unused variable (lib/artist_releases.py:63)
pipeline_status  # unused variable (lib/artist_releases.py:64)
flac_streaminfo_md5  # unused function (lib/audio_hash.py:173)
_.local_track_count  # unused attribute (lib/beets.py:98)
_.is_target  # unused attribute (lib/beets.py:114)
invalidate_secret_cache  # unused function (lib/config.py:50)
track_prepend_artist  # unused variable (lib/config.py:77)
search_for_tracks  # unused variable (lib/config.py:81)
pipeline_db_enabled  # unused variable (lib/config.py:160)
active_total  # unused variable (lib/disk_coverage_service.py:31)
off_disk_total  # unused variable (lib/disk_coverage_service.py:33)
inverse_total  # unused variable (lib/disk_coverage_service.py:37)
inverse  # unused variable (lib/disk_coverage_service.py:43)
_.quarantine_error  # unused attribute (lib/dispatch/helpers.py:186)
harvest_terminal_transfer_evidence  # dynamically resolved by lib/convergence.py registry (lib/download.py:375)
_.download_folder  # JSONB validation evidence field (lib/download_validation.py)
_.denylisted_users  # JSONB validation evidence field (lib/download_rejection.py)
IMPORT_JOB_ACTIVE_STATUSES  # unused variable (lib/import_queue.py:30)
IMPORT_JOB_IMPORTABLE_PREVIEW_STATUSES  # unused variable (lib/import_queue.py:63)
_PinDBProto  # unused class (lib/jellyfin_pin_service.py:59)
pipeline_request_id  # unused variable (lib/library_delete_service.py:99)
reported_at  # unused variable (lib/pipeline_db/_shared.py:247)
next_plan_ordinal  # unused variable (lib/pipeline_db/_shared.py:476)
plan_cycle_count  # unused variable (lib/pipeline_db/_shared.py:477)
legacy_search_log_count  # unused variable (lib/pipeline_db/_shared.py:517)
new_cycle_count  # unused variable (lib/pipeline_db/_shared.py:707)
_.get_field_resolution  # unused method (lib/pipeline_db/misc.py:266)
_PinDBProto  # unused class (lib/plex_pin_service.py:42)
existing_suspect_pct  # unused variable (lib/quality/import_result_types.py:53)
quarantine_error  # unused variable (lib/quality/import_result_types.py:131)
beets_id  # unused variable (lib/quality/import_result_types.py:140)
moved_siblings  # unused variable (lib/quality/import_result_types.py:148)
beets_log  # unused variable (lib/quality/import_result_types.py:188)
v0_verification_bitrate  # unused variable (lib/quality/import_result_types.py:191)
quality_evidence_provenance  # unused variable (lib/quality/import_result_types.py:196)
special_buckets  # wire metadata consumed by API/CLI JSON clients and tests (lib/quarantine_triage_service.py:43)
MIN  # unused variable (lib/quality/ranks.py:51)
distance_breakdown  # unused variable (lib/quality/wire_types.py:113)
is_target  # unused variable (lib/quality/wire_types.py:114)
local_track_count  # unused variable (lib/quality/wire_types.py:182)
download_folder  # unused variable (lib/quality/wire_types.py:187)
denylisted_users  # unused variable (lib/quality/wire_types.py:190)
escalation_threshold  # unused variable (lib/search.py:502)
ALL_FAILURE_CLASSES  # unused variable (lib/search_classification.py:48)
FAILURE_CLASS_UNKNOWN  # unused variable (lib/search_plan_service.py:157)
schema_version  # unused variable (lib/sidecar.py:87)
remote_filename  # unused variable (lib/slskd_client.py:66)
percent_complete  # unused variable (lib/slskd_client.py:121)
converge_slskd_searches  # dynamically resolved by lib/convergence.py registry (lib/slskd_searches.py:68)
prune_transfer_ledger_cycle  # dynamically resolved by lib/convergence.py registry (lib/slskd_transfer_ledger.py:33)
prune_terminal_pin_rows_cycle  # dynamically resolved by lib/convergence.py registry (lib/pin_retention.py:19)
converge_slskd_orphans  # dynamically resolved by lib/convergence.py registry (lib/slskd_transfers.py:534)
purge_completed_transfers  # dynamically resolved by lib/convergence.py registry (lib/slskd_transfers.py:658)
reap_disk_orphans  # dynamically resolved by lib/convergence.py registry (lib/slskd_transfers.py:987)
aborted  # unused variable (lib/slskd_transfers.py:792)
LAME_LOWPASS  # unused variable (lib/spectral_check.py:31)
error_count  # unused variable (lib/spectral_check.py:356)
error_count  # unused variable (lib/spectral_check.py:360)
_.is_ready  # unused property (lib/startup_reconciliation.py:123)
_DBProto  # unused class (lib/startup_reconciliation.py:129)
_.check_hostname  # unused attribute (lib/util.py:657)
_.verify_mode  # unused attribute (lib/util.py:658)
deleted_verified_lossless_parent  # unused variable (lib/wrong_match_cleanup_service.py:160)
kept_would_import  # unused variable (lib/wrong_match_cleanup_service.py:161)
kept_uncertain  # unused variable (lib/wrong_match_cleanup_service.py:162)
skipped_candidate_evidence_missing  # unused variable (lib/wrong_match_cleanup_service.py:163)
skipped_candidate_evidence_stale  # unused variable (lib/wrong_match_cleanup_service.py:164)
skipped_current_evidence_missing  # unused variable (lib/wrong_match_cleanup_service.py:165)
skipped_current_evidence_stale  # unused variable (lib/wrong_match_cleanup_service.py:166)
skipped_current_evidence_failed  # unused variable (lib/wrong_match_cleanup_service.py:167)
skipped_active_job  # unused variable (lib/wrong_match_cleanup_service.py:168)
skipped_invalid_row  # unused variable (lib/wrong_match_cleanup_service.py:169)
skipped_missing_path  # unused variable (lib/wrong_match_cleanup_service.py:170)
skipped_operational  # unused variable (lib/wrong_match_cleanup_service.py:171)
delete_failed  # unused variable (lib/wrong_match_cleanup_service.py:172)
group_empty  # unused variable (lib/wrong_match_delete_service.py:100)
worker_claimed_at  # unused variable (lib/youtube_ingest_service.py:160)
blocking_resource  # unused variable (lib/youtube_ingest_service.py:196)
_.check_hostname  # unused attribute (scripts/plex_dupes_audit.py:27)
_.verify_mode  # unused attribute (scripts/plex_dupes_audit.py:28)
_.check_hostname  # unused attribute (scripts/plex_dupes_merge.py:33)
_.verify_mode  # unused attribute (scripts/plex_dupes_merge.py:34)
daemon_threads  # unused variable (scripts/web_dev_server.py:81)
_.log_message  # unused method (scripts/web_dev_server.py:111)
_.do_GET  # unused method (scripts/web_dev_server.py:114)
_.do_POST  # unused method (scripts/web_dev_server.py:129)
_.do_OPTIONS  # unused method (scripts/web_dev_server.py:144)
request_min_bitrate  # unused variable (web/classify.py:76)
request_source  # unused variable (web/classify.py:79)
youtube_metadata  # unused variable (web/classify.py:80)
disambiguation_detail  # msgspec outbound field projected via to_builtins (web/classify.py:125)
wrong_match_triage_action  # msgspec outbound field projected via to_builtins (web/classify.py:127)
wrong_match_triage_summary  # msgspec outbound field projected via to_builtins (web/classify.py:128)
wrong_match_triage_reason  # msgspec outbound field projected via to_builtins (web/classify.py:129)
wrong_match_triage_preview_verdict  # msgspec outbound field projected via to_builtins (web/classify.py:130)
wrong_match_triage_preview_decision  # msgspec outbound field projected via to_builtins (web/classify.py:131)
wrong_match_triage_stage_chain  # msgspec outbound field projected via to_builtins (web/classify.py:132)
wrong_match_triage_detail  # msgspec outbound field projected via to_builtins (web/classify.py:133)
spectral_attempted  # msgspec outbound field projected via to_builtins (web/classify.py)
spectral_error  # msgspec outbound field projected via to_builtins (web/classify.py)
existing_spectral_attempted  # msgspec outbound field projected via to_builtins (web/classify.py)
existing_spectral_error  # msgspec outbound field projected via to_builtins (web/classify.py)
contactinfo  # unused variable (web/discogs.py:479)
data_quality  # unused variable (web/discogs.py:480)
anv  # unused variable (web/discogs.py:491)
request_min_bitrate  # unused variable (web/download_history_view.py:73)
request_source  # unused variable (web/download_history_view.py:76)
youtube_metadata  # unused variable (web/download_history_view.py:77)
disambiguation_detail  # msgspec outbound field serialized by to_dict (web/download_history_view.py:53)
wrong_match_triage_action  # msgspec outbound field serialized by to_dict (web/download_history_view.py:55)
wrong_match_triage_summary  # msgspec outbound field serialized by to_dict (web/download_history_view.py:56)
wrong_match_triage_reason  # msgspec outbound field serialized by to_dict (web/download_history_view.py:57)
wrong_match_triage_preview_verdict  # msgspec outbound field serialized by to_dict (web/download_history_view.py:58)
wrong_match_triage_preview_decision  # msgspec outbound field serialized by to_dict (web/download_history_view.py:59)
wrong_match_triage_stage_chain  # msgspec outbound field serialized by to_dict (web/download_history_view.py:60)
wrong_match_triage_detail  # msgspec outbound field serialized by to_dict (web/download_history_view.py:61)
spectral_attempted  # msgspec outbound field serialized by to_dict (web/download_history_view.py)
spectral_error  # msgspec outbound field serialized by to_dict (web/download_history_view.py)
existing_spectral_attempted  # msgspec outbound field serialized by to_dict (web/download_history_view.py)
existing_spectral_error  # msgspec outbound field serialized by to_dict (web/download_history_view.py)
samplerate  # unused variable (web/library_album_detail_service.py:116)
bitdepth  # unused variable (web/library_album_detail_service.py:117)
mb_releasegroupid  # unused variable (web/library_album_detail_service.py:141)
artpath  # unused variable (web/library_album_detail_service.py:150)
pipeline_status  # unused variable (web/library_album_detail_service.py:154)
pipeline_source  # unused variable (web/library_album_detail_service.py:155)
pipeline_min_bitrate  # unused variable (web/library_album_detail_service.py:156)
upgrade_queued  # unused variable (web/library_album_detail_service.py:159)
mb_releasegroupid  # unused variable (web/library_album_row.py:65)
pipeline_status  # unused variable (web/library_album_row.py:76)
upgrade_queued  # unused variable (web/library_album_row.py:78)
library_rank  # unused variable (web/library_album_row.py:79)
OverlayPipelineDB  # unused class (web/overlay.py:20)
OverlayBeetsDB  # unused class (web/overlay.py:29)
unclassified_routes  # unused function (web/routes/_registry.py:137)
missing_or_empty_descriptions  # unused function (web/routes/_registry.py:148)
_.close_connection  # unused attribute (web/routes/imports.py:577)
_._must_be_true  # unused method (web/routes/imports.py:882)
confirm  # unused variable (web/routes/library.py:40)
_._at_least_one_release_id  # unused method (web/routes/pipeline_mutations.py:184)
_._exactly_one_target  # unused method (web/routes/search_plan.py:403)
protocol_version  # unused variable (web/server.py:265)
_.log_message  # unused method (web/server.py:284)
_.do_GET  # unused method (web/server.py:363)
_.close_connection  # unused attribute (web/server.py:403)
_.close_connection  # unused attribute (web/server.py:415)
_.do_POST  # unused method (web/server.py:418)
_.close_connection  # unused attribute (web/server.py:458)
_.close_connection  # unused attribute (web/server.py:467)
_.do_OPTIONS  # unused method (web/server.py:480)
