# Vulture whitelist — baseline of names vulture flagged as "unused" on the
# pristine main branch. References here are treated as real uses, so vulture
# only reports *new* dead code introduced after this baseline was generated.
#
# Regenerate the full list:
#   nix-shell --run "vulture --make-whitelist lib/ web/ harness/ scripts/ \
#       cratedigger.py album_source.py > tools/vulture/whitelist.py"
#
# Most entries fall into one of these categories — left in the baseline because
# vulture cannot see they're actually used:
#   - msgspec.Struct / @dataclass fields read via serialization, not attribute access
#   - beets ImportSession hook overrides (choose_match, resolve_duplicate, ...)
#   - SQL DictRow column attribute lookups
#   - Route handlers registered via _FUNC_GET_ROUTES / _FUNC_POST_ROUTES dispatch
#   - Tuple unpacking targets where one position is intentionally discarded
#
# To audit the baseline for genuinely-dead candidates worth deleting:
#   bash scripts/find_dead_code.sh --baseline    # runs without this whitelist
#
# Pyright / runtime ignores this file — it's Python only so vulture can parse
# bare name expressions as references.

medium_format  # unused variable (album_source.py:27)
foreign_artist_id  # unused variable (album_source.py:54)
db_release_group_year  # unused variable (album_source.py:66)
albumId  # unused variable (cratedigger.py:25)
mediumNumber  # unused variable (cratedigger.py:27)
_.choose_match  # unused method (harness/beets_harness.py:406)
_.choose_item  # unused method (harness/beets_harness.py:434)
_.resolve_duplicate  # unused method (harness/beets_harness.py:499)
_.should_remove_duplicates  # unused attribute (harness/beets_harness.py:541)
_.should_resume  # unused method (harness/beets_harness.py:545)
_.quality_evidence_provenance  # unused attribute (harness/import_one.py:1290)
_.beets_log  # unused attribute (harness/import_one.py:1328)
_.existing_suspect_pct  # unused attribute (harness/import_one.py:1573)
_.v0_verification_bitrate  # unused attribute (harness/import_one.py:1926)
_.beets_log  # unused attribute (harness/import_one.py:2020)
library_status  # unused variable (lib/artist_releases.py:63)
pipeline_status  # unused variable (lib/artist_releases.py:64)
flac_streaminfo_md5  # unused function (lib/audio_hash.py:173)
_.local_track_count  # unused attribute (lib/beets.py:98)
_.is_target  # unused attribute (lib/beets.py:114)
invalidate_secret_cache  # unused function (lib/config.py:50)
track_prepend_artist  # unused variable (lib/config.py:77)
search_for_tracks  # unused variable (lib/config.py:81)
pipeline_db_enabled  # unused variable (lib/config.py:143)
_.download_folder  # unused attribute (lib/download.py:1173)
_.denylisted_users  # unused attribute (lib/download.py:1555)
_.quarantine_error  # unused attribute (lib/import_dispatch.py:1246)
IMPORT_JOB_ACTIVE_STATUSES  # unused variable (lib/import_queue.py:20)
IMPORT_JOB_IMPORTABLE_PREVIEW_STATUSES  # unused variable (lib/import_queue.py:53)
pipeline_request_id  # unused variable (lib/library_delete_service.py:99)
reported_at  # unused variable (lib/pipeline_db.py:231)
SEARCH_LOG_STAGE_RECONCILIATION  # unused variable (lib/pipeline_db.py:256)
next_plan_ordinal  # unused variable (lib/pipeline_db.py:413)
plan_cycle_count  # unused variable (lib/pipeline_db.py:414)
legacy_search_log_count  # unused variable (lib/pipeline_db.py:454)
CACHE_ATTRIBUTION_PER_SEARCH  # unused variable (lib/pipeline_db.py:469)
new_cycle_count  # unused variable (lib/pipeline_db.py:619)
_.heartbeat_import_job  # unused method (lib/pipeline_db.py:1228)
_.list_stale_running_import_jobs  # unused method (lib/pipeline_db.py:1282)
_.fail_stale_running_import_jobs  # unused method (lib/pipeline_db.py:1299)
_.mark_import_job_preview_blocked  # unused method (lib/pipeline_db.py:1518)
_.list_stale_import_preview_jobs  # unused method (lib/pipeline_db.py:1564)
_.set_manual  # unused method (lib/pipeline_db.py:1988)
_.update_v0_probe_state  # unused method (lib/pipeline_db.py:2080)
_.reset_search_attempts  # unused method (lib/pipeline_db.py:2590)
_.update_imported_path_by_release_id  # unused method (lib/pipeline_db.py:2605)
_.clear_download_state  # unused method (lib/pipeline_db.py:2826)
_.get_search_history_batch  # unused method (lib/pipeline_db.py:3583)
_.get_user_cooldowns  # unused method (lib/pipeline_db.py:4804)
_._fetch_plan_items  # unused method (lib/pipeline_db.py:5309)
_.get_field_resolution  # unused method (lib/pipeline_db.py:6053)
V0_PROBE_KINDS  # unused variable (lib/quality.py:22)
QUALITY_FLAC_ONLY  # unused variable (lib/quality.py:34)
distance_breakdown  # unused variable (lib/quality.py:323)
is_target  # unused variable (lib/quality.py:324)
local_track_count  # unused variable (lib/quality.py:392)
download_folder  # unused variable (lib/quality.py:397)
denylisted_users  # unused variable (lib/quality.py:400)
MIN  # unused variable (lib/quality.py:1026)
existing_suspect_pct  # unused variable (lib/quality.py:1756)
quarantine_error  # unused variable (lib/quality.py:1834)
beets_id  # unused variable (lib/quality.py:1843)
moved_siblings  # unused variable (lib/quality.py:1851)
beets_log  # unused variable (lib/quality.py:1891)
v0_verification_bitrate  # unused variable (lib/quality.py:1894)
quality_evidence_provenance  # unused variable (lib/quality.py:1899)
CODEC_TO_EXT  # unused variable (lib/quality.py:3018)
escalation_threshold  # unused variable (lib/search.py:349)
FAILURE_CLASS_UNKNOWN  # unused variable (lib/search_plan_service.py:72)
sessions_configured  # unused variable (lib/slskd_client.py:24)
configured  # unused variable (lib/slskd_client.py:25)
LAME_LOWPASS  # unused variable (lib/spectral_check.py:31)
error_count  # unused variable (lib/spectral_check.py:356)
error_count  # unused variable (lib/spectral_check.py:360)
_.is_ready  # unused property (lib/startup_reconciliation.py:123)
_DBProto  # unused class (lib/startup_reconciliation.py:129)
clear_download_state  # unused variable (lib/transitions.py:323)
deleted_verified_lossless_parent  # unused variable (lib/wrong_match_cleanup_service.py:95)
kept_would_import  # unused variable (lib/wrong_match_cleanup_service.py:96)
kept_uncertain  # unused variable (lib/wrong_match_cleanup_service.py:97)
skipped_candidate_evidence_missing  # unused variable (lib/wrong_match_cleanup_service.py:98)
skipped_candidate_evidence_stale  # unused variable (lib/wrong_match_cleanup_service.py:99)
skipped_current_evidence_missing  # unused variable (lib/wrong_match_cleanup_service.py:100)
skipped_current_evidence_stale  # unused variable (lib/wrong_match_cleanup_service.py:101)
skipped_current_evidence_failed  # unused variable (lib/wrong_match_cleanup_service.py:102)
skipped_active_job  # unused variable (lib/wrong_match_cleanup_service.py:103)
skipped_invalid_row  # unused variable (lib/wrong_match_cleanup_service.py:104)
skipped_missing_path  # unused variable (lib/wrong_match_cleanup_service.py:105)
skipped_operational  # unused variable (lib/wrong_match_cleanup_service.py:106)
delete_failed  # unused variable (lib/wrong_match_cleanup_service.py:107)
group_empty  # unused variable (lib/wrong_match_delete_service.py:68)
IMPORT_ONE  # unused variable (scripts/pipeline_cli.py:1222)
_.check_hostname  # unused attribute (scripts/plex_dupes_audit.py:27)
_.verify_mode  # unused attribute (scripts/plex_dupes_audit.py:28)
_.check_hostname  # unused attribute (scripts/plex_dupes_merge.py:33)
_.verify_mode  # unused attribute (scripts/plex_dupes_merge.py:34)
daemon_threads  # unused variable (scripts/web_dev_server.py:81)
_.log_message  # unused method (scripts/web_dev_server.py:111)
_.do_GET  # unused method (scripts/web_dev_server.py:114)
_.do_POST  # unused method (scripts/web_dev_server.py:129)
_.do_OPTIONS  # unused method (scripts/web_dev_server.py:144)
request_status  # unused variable (web/classify.py:70)
request_min_bitrate  # unused variable (web/classify.py:71)
contactinfo  # unused variable (web/discogs.py:423)
data_quality  # unused variable (web/discogs.py:424)
anv  # unused variable (web/discogs.py:435)
request_status  # unused variable (web/download_history_view.py:72)
request_min_bitrate  # unused variable (web/download_history_view.py:73)
samplerate  # unused variable (web/library_album_detail_service.py:116)
bitdepth  # unused variable (web/library_album_detail_service.py:117)
mb_releasegroupid  # unused variable (web/library_album_detail_service.py:141)
added  # unused variable (web/library_album_detail_service.py:143)
artpath  # unused variable (web/library_album_detail_service.py:150)
pipeline_status  # unused variable (web/library_album_detail_service.py:154)
pipeline_source  # unused variable (web/library_album_detail_service.py:155)
pipeline_min_bitrate  # unused variable (web/library_album_detail_service.py:156)
upgrade_queued  # unused variable (web/library_album_detail_service.py:159)
mb_releasegroupid  # unused variable (web/library_album_row.py:65)
added  # unused variable (web/library_album_row.py:67)
pipeline_status  # unused variable (web/library_album_row.py:76)
upgrade_queued  # unused variable (web/library_album_row.py:78)
library_rank  # unused variable (web/library_album_row.py:79)
_._must_be_true  # unused method (web/routes/imports.py:966)
confirm  # unused variable (web/routes/library.py:67)
_._exactly_one_target  # unused method (web/routes/pipeline.py:971)
_._at_least_one_release_id  # unused method (web/routes/pipeline.py:1406)
_.log_message  # unused method (web/server.py:242)
_.do_GET  # unused method (web/server.py:299)
_.do_POST  # unused method (web/server.py:339)
_.do_OPTIONS  # unused method (web/server.py:384)
ALL_FAILURE_CLASSES  # exported for tests (lib/search_classification.py:48)
cycles_observed  # msgspec.Struct field (lib/unfindable_detection_service.py:161)
current_category  # msgspec.Struct field (lib/unfindable_detection_service.py:182)
