#!/usr/bin/env python3
"""Generate and validate Codex adapters from shared Claude-format sources."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
CLAUDE_AGENTS = ROOT / ".claude" / "agents"
CODEX_AGENTS = ROOT / ".codex" / "agents"
MCP_SOURCE = ROOT / ".mcp.json"
CODEX_CONFIG = ROOT / ".codex" / "config.toml"
GENERATED_HEADER = "# Generated by tools/generate-ai-adapters.py; do not edit.\n"


class AdapterError(RuntimeError):
    """Raised when a shared source cannot be represented safely for Codex."""


def toml_value(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        entries = (
            f"{toml_value(str(key))} = {toml_value(item)}"
            for key, item in value.items()
        )
        return "{ " + ", ".join(entries) + " }"
    raise AdapterError(f"unsupported TOML value: {value!r}")


def parse_scalar(raw: str) -> Any:
    raw = raw.strip()
    if raw in {"[]", "{}"} or raw.startswith(("[", "{", '"')):
        try:
            return json.loads(raw)
        except json.JSONDecodeError as exc:
            raise AdapterError(
                f"frontmatter value must use JSON-compatible syntax: {raw}"
            ) from exc
    if raw in {"true", "false"}:
        return raw == "true"
    return raw


def parse_agent(path: Path) -> tuple[str, str, str, dict[str, dict[str, Any]]]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(.*?)\n---\n(.*)\Z", text, re.DOTALL)
    if not match:
        raise AdapterError(f"{path.relative_to(ROOT)}: expected YAML frontmatter")

    header, body = match.groups()
    fields: dict[str, Any] = {}
    servers: dict[str, dict[str, Any]] = {}
    lines = header.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if line == "mcpServers:":
            index += 1
            while index < len(lines) and lines[index].startswith("  - "):
                server_match = re.fullmatch(
                    r"  - ([A-Za-z0-9_-]+):", lines[index]
                )
                if not server_match:
                    raise AdapterError(
                        f"{path.relative_to(ROOT)}: invalid MCP server declaration"
                    )
                server_name = server_match.group(1)
                server: dict[str, Any] = {}
                index += 1
                while index < len(lines) and lines[index].startswith("      "):
                    key, separator, raw = lines[index].strip().partition(":")
                    if not separator:
                        raise AdapterError(
                            f"{path.relative_to(ROOT)}: invalid MCP field"
                        )
                    server[key] = parse_scalar(raw)
                    index += 1
                servers[server_name] = server
            continue
        if line.startswith(" "):
            raise AdapterError(
                f"{path.relative_to(ROOT)}: unsupported nested frontmatter: {line}"
            )
        key, separator, raw = line.partition(":")
        if not separator:
            raise AdapterError(
                f"{path.relative_to(ROOT)}: invalid frontmatter line: {line}"
            )
        fields[key] = parse_scalar(raw)
        index += 1

    name = fields.get("name")
    description = fields.get("description")
    if not isinstance(name, str) or not isinstance(description, str):
        raise AdapterError(
            f"{path.relative_to(ROOT)}: name and description are required"
        )
    if name != path.stem:
        raise AdapterError(f"{path.relative_to(ROOT)}: name must match filename")
    return name, description, body.rstrip() + "\n", servers


def normalize_mcp(server: dict[str, Any], source: str) -> dict[str, Any]:
    result = dict(server)
    server_type = result.pop("type", None)
    if server_type not in {None, "stdio", "http"}:
        raise AdapterError(f"{source}: unsupported MCP type {server_type!r}")
    if "headers" in result:
        if "http_headers" in result:
            raise AdapterError(f"{source}: use either headers or http_headers")
        result["http_headers"] = result.pop("headers")
    allowed = {
        "args", "bearer_token_env_var", "command", "cwd", "disabled_tools",
        "enabled", "enabled_tools", "env", "env_http_headers", "env_vars",
        "http_headers", "required", "startup_timeout_sec", "tool_timeout_sec",
        "url",
    }
    unknown = sorted(set(result) - allowed)
    if unknown:
        raise AdapterError(f"{source}: unsupported MCP fields: {', '.join(unknown)}")
    if ("command" in result) == ("url" in result):
        raise AdapterError(f"{source}: exactly one of command or url is required")
    return result


def render_mcp_tables(servers: dict[str, dict[str, Any]]) -> str:
    chunks = []
    preferred_order = [
        "command", "args", "url", "bearer_token_env_var", "cwd", "env_vars",
        "env", "http_headers", "env_http_headers", "enabled", "required",
        "startup_timeout_sec", "tool_timeout_sec", "enabled_tools",
        "disabled_tools",
    ]
    for name in sorted(servers):
        normalized = normalize_mcp(servers[name], f"MCP server {name}")
        lines = [f"[mcp_servers.{toml_value(name)}]"]
        lines.extend(
            f"{key} = {toml_value(normalized[key])}"
            for key in preferred_order
            if key in normalized
        )
        chunks.append("\n".join(lines))
    return "\n\n".join(chunks)


def expected_outputs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for path in sorted(CLAUDE_AGENTS.glob("*.md")):
        name, description, body, servers = parse_agent(path)
        content = [
            GENERATED_HEADER.rstrip(),
            f"name = {toml_value(name)}",
            f"description = {toml_value(description)}",
            f"developer_instructions = {toml_value(body)}",
        ]
        if servers:
            content.extend(["", render_mcp_tables(servers)])
        outputs[CODEX_AGENTS / f"{name}.toml"] = "\n".join(content) + "\n"

    data = json.loads(MCP_SOURCE.read_text(encoding="utf-8"))
    servers = data.get("mcpServers")
    if not isinstance(servers, dict):
        raise AdapterError(".mcp.json: mcpServers must be an object")
    config = GENERATED_HEADER
    if servers:
        config += "\n" + render_mcp_tables(servers) + "\n"
    outputs[CODEX_CONFIG] = config
    return outputs


def validate_skill(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        return [f"{path.relative_to(ROOT)} must start with YAML frontmatter"]
    fields = {}
    for line in match.group(1).splitlines():
        key, separator, value = line.partition(":")
        if separator:
            fields[key] = value.strip()
    errors = []
    if fields.get("name") != path.parent.name:
        errors.append(f"{path.relative_to(ROOT)} name must match its directory")
    if not fields.get("description"):
        errors.append(f"{path.relative_to(ROOT)} needs a description")
    return errors


def validate_shared_surfaces() -> list[str]:
    errors: list[str] = []
    links = {
        ROOT / "AGENTS.md": ROOT / "CLAUDE.md",
        ROOT / ".agents" / "skills": ROOT / ".claude" / "skills",
    }
    for link, target in links.items():
        if not link.is_symlink() or link.resolve() != target.resolve():
            errors.append(
                f"{link.relative_to(ROOT)} must symlink to {target.relative_to(ROOT)}"
            )

    for legacy in (
        ROOT / ".claude" / "commands",
        ROOT / ".codex" / "CODEX.md",
        ROOT / ".codex" / "skills",
    ):
        if legacy.exists() or legacy.is_symlink():
            errors.append(f"{legacy.relative_to(ROOT)} is legacy")

    skill_root = ROOT / ".claude" / "skills"
    for skill_dir in sorted(path for path in skill_root.iterdir() if path.is_dir()):
        skill = skill_dir / "SKILL.md"
        if not skill.is_file():
            errors.append(f"{skill_dir.relative_to(ROOT)} is missing SKILL.md")
        else:
            errors.extend(validate_skill(skill))

    claude_size = (ROOT / "CLAUDE.md").stat().st_size
    if claude_size > 32 * 1024:
        errors.append("CLAUDE.md exceeds Codex's 32 KiB instruction limit")
    return errors


def write_outputs(outputs: dict[Path, str]) -> None:
    CODEX_AGENTS.mkdir(parents=True, exist_ok=True)
    expected_paths = set(outputs)
    for stale in CODEX_AGENTS.glob("*.toml"):
        if stale not in expected_paths:
            stale.unlink()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_outputs(outputs: dict[Path, str]) -> list[str]:
    errors = validate_shared_surfaces()
    expected_paths = set(outputs)
    actual_agents = set(CODEX_AGENTS.glob("*.toml")) if CODEX_AGENTS.exists() else set()
    for stale in sorted(actual_agents - expected_paths):
        errors.append(f"stale generated agent: {stale.relative_to(ROOT)}")
    for path, content in outputs.items():
        if not path.exists():
            errors.append(f"missing generated adapter: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"generated adapter is stale: {path.relative_to(ROOT)}")
        else:
            try:
                tomllib.loads(content)
            except tomllib.TOMLDecodeError as exc:
                errors.append(f"invalid generated TOML {path.relative_to(ROOT)}: {exc}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate without writing")
    args = parser.parse_args()
    try:
        outputs = expected_outputs()
        if args.check:
            errors = check_outputs(outputs)
            if errors:
                for error in errors:
                    print(f"ERROR: {error}", file=sys.stderr)
                return 1
            print(f"AI adapters are current ({len(outputs) - 1} agents, 1 config).")
        else:
            write_outputs(outputs)
            print(f"Generated {len(outputs) - 1} Codex agents and 1 config.")
    except (AdapterError, json.JSONDecodeError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
